spring.datasource.url=jdbc:mysql://localhost:3306/SwimAI
spring.datasource.username=root
spring.datasource.password=Diablo@5241

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect